name: Direct Git Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy via Git Clone
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem
        
        # EC2上で直接git cloneする
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@54.249.2.157 << 'EOF' || true
        echo "=== Direct Git Deploy ==="
        
        # Cleanup
        sudo rm -rf /var/www/html/*
        
        # Clone repository
        cd /tmp
        rm -rf xsyumeno-temp
        git clone https://github.com/Naoki-Takahashi0420/metore_system.git xsyumeno-temp
        
        # Move to web root
        sudo cp -r xsyumeno-temp/* /var/www/html/
        cd /var/www/html
        
        # Create .env
        sudo tee .env << 'ENV' > /dev/null
        APP_NAME=Xsyumeno
        APP_ENV=production
        APP_KEY=base64:FhDmJJEPuQPAz6t5HMt6qTVSYLs7pJg7xLDgBEcVHHg=
        APP_DEBUG=true
        APP_URL=http://54.249.2.157
        
        DB_CONNECTION=mysql
        DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
        DB_PORT=3306
        DB_DATABASE=xsyumenodb
        DB_USERNAME=admin
        DB_PASSWORD=Xsyumeno2024#!
        
        LOG_CHANNEL=stack
        CACHE_DRIVER=file
        SESSION_DRIVER=database
        QUEUE_CONNECTION=database
        ENV
        
        # Install composer if needed
        if ! command -v composer &> /dev/null; then
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
        fi
        
        # Install dependencies
        export COMPOSER_ALLOW_SUPERUSER=1
        sudo composer install --no-dev --optimize-autoloader
        
        # Laravel setup
        sudo php artisan key:generate
        sudo php artisan storage:link
        sudo php artisan config:cache
        sudo php artisan migrate --force
        
        # Fix permissions
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html
        sudo chmod -R 775 storage bootstrap/cache
        
        # Restart services
        sudo systemctl restart nginx php8.1-fpm
        
        echo "=== Deploy Complete ==="
        EOF
        
        rm key.pem
        
        # Test from outside
        echo "Testing..."
        curl -I http://54.249.2.157/