name: Fix Deploy

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fix EC2 Setup
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem
        
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.112.39.129 << 'FIX'
        echo "=== Fixing EC2 Setup ==="
        
        # Create web directory
        sudo mkdir -p /var/www/html
        
        # Clone repository
        cd /var/www
        sudo rm -rf html
        sudo git clone https://github.com/Naoki-Takahashi0420/metore_system.git html
        
        # Check if clone succeeded
        if [ ! -d /var/www/html ]; then
          echo "ERROR: Git clone failed!"
          exit 1
        fi
        
        cd /var/www/html
        
        # Install Composer if not exists
        if ! command -v composer &> /dev/null; then
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
        fi
        
        # Install dependencies
        sudo composer install --no-dev --optimize-autoloader
        
        # Create .env
        sudo tee .env << 'ENV' > /dev/null
        APP_NAME=Xsyumeno
        APP_ENV=production
        APP_KEY=base64:FhDmJJEPuQPAz6t5HMt6qTVSYLs7pJg7xLDgBEcVHHg=
        APP_DEBUG=true
        APP_URL=http://3.112.39.129
        
        DB_CONNECTION=mysql
        DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
        DB_PORT=3306
        DB_DATABASE=xsyumenodb
        DB_USERNAME=admin
        DB_PASSWORD=Xsyumeno2024#!
        
        LOG_CHANNEL=stack
        CACHE_DRIVER=file
        SESSION_DRIVER=file
        QUEUE_CONNECTION=sync
        ENV
        
        # Laravel setup
        sudo php artisan key:generate
        sudo php artisan storage:link
        sudo php artisan config:cache
        sudo php artisan route:cache
        sudo php artisan view:cache
        sudo php artisan migrate --force
        
        # Set permissions
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html
        sudo chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
        
        # Restart services
        sudo systemctl restart nginx php8.3-fpm
        
        # Test
        echo -e "\nTesting deployment:"
        curl -I http://localhost/
        
        echo -e "\n=== Fix Complete ==="
        FIX
        
        rm key.pem