name: Deploy via S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz --exclude='.git' --exclude='node_modules' .
      
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          # Create S3 bucket if not exists
          aws s3 mb s3://xsyumeno-deployments --region ap-northeast-1 || true
          
          # Upload deployment package
          aws s3 cp deploy.tar.gz s3://xsyumeno-deployments/latest.tar.gz
          
          # Create deployment flag
          echo "$(date)" | aws s3 cp - s3://xsyumeno-deployments/deploy-flag.txt