name: Simple Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy via AWS SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          # SSM経由でコマンド実行（SSHより簡単）
          aws ssm send-command \
            --instance-ids i-0f20a2a9e7d202c75 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /var/www/html && sudo git pull && sudo systemctl restart nginx"]' \
            --output text