name: Setup EC2 Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup EC2 with PHP 8.2
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: 54.64.54.226
        EC2_USER: ubuntu
      run: |
        echo "$EC2_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i deploy_key.pem ${EC2_USER}@${EC2_HOST} << 'SETUP'
        set -e
        echo "=== EC2環境セットアップ ==="
        
        # PHP 8.2リポジトリ追加
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update
        
        # PHP 8.2とモジュールをインストール
        sudo apt-get install -y \
          php8.2 \
          php8.2-fpm \
          php8.2-mysql \
          php8.2-xml \
          php8.2-mbstring \
          php8.2-curl \
          php8.2-zip \
          php8.2-intl \
          php8.2-gd \
          php8.2-dom
        
        # Nginxでphp8.2-fpmを使用するよう設定
        sudo tee /etc/nginx/sites-available/default << 'NGINX'
        server {
            listen 80 default_server;
            listen [::]:80 default_server;
            
            root /var/www/html/public;
            index index.php index.html;
            
            server_name _;
            
            location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
            }
            
            location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
            }
            
            location ~ /\.ht {
                deny all;
            }
        }
        NGINX
        
        # Composer最新版インストール
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        
        # サービス再起動
        sudo systemctl restart nginx php8.2-fpm
        
        # PHP バージョン確認
        php --version
        echo "=== セットアップ完了 ==="
        SETUP
        
        rm deploy_key.pem