name: Add LINE Test User ID

on:
  workflow_dispatch:

jobs:
  add-line-test-user:
    runs-on: ubuntu-latest

    steps:
    - name: Add LINE_TEST_USER_ID to .env
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: 54.64.54.226
        EC2_USER: ubuntu
      run: |
        echo "$EC2_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i deploy_key.pem ${EC2_USER}@${EC2_HOST} << 'ENVSSH'
        cd /var/www/html

        echo "=== Current .env check ==="
        if grep -q "LINE_TEST_USER_ID" .env; then
          echo "LINE_TEST_USER_ID already exists"
        else
          echo "LINE_TEST_USER_ID not found, adding..."
          sudo bash -c 'echo "" >> .env'
          sudo bash -c 'echo "# LINE Test User ID (開発者用)" >> .env'
          sudo bash -c 'echo "LINE_TEST_USER_ID=Uc37e9137beadca4a6d5c04aaada19ab1" >> .env'
          echo "✅ LINE_TEST_USER_ID added"
        fi

        echo "=== Last 5 lines of .env ==="
        sudo tail -5 .env

        echo "=== Clear config cache ==="
        sudo php artisan config:clear

        echo "✅ Complete!"
        ENVSSH

        rm deploy_key.pem
