name: Check Error Logs

on:
  workflow_dispatch:

jobs:
  check-logs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Laravel error logs
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            echo "=== PHP エラーログ ==="
            sudo tail -50 /var/log/php8.3-fpm.log || echo "PHP-FPM log not found"
            
            echo ""
            echo "=== Nginx エラーログ ==="
            sudo tail -30 /var/log/nginx/error.log
            
            echo ""
            echo "=== Laravel エラーログ ==="
            if [ -f /var/www/html/current/storage/logs/laravel.log ]; then
              sudo tail -100 /var/www/html/current/storage/logs/laravel.log
            else
              echo "Laravel log not found"
              echo "Checking storage directory:"
              ls -la /var/www/html/current/storage/
              ls -la /var/www/html/current/storage/logs/ 2>/dev/null || echo "logs directory not found"
            fi
            
            echo ""
            echo "=== APP_KEY 確認 ==="
            if [ -f /var/www/html/current/.env ]; then
              grep APP_KEY /var/www/html/current/.env | head -1
            else
              echo ".env not found"
            fi
            
            echo ""
            echo "=== Cached config 確認 ==="
            if [ -f /var/www/html/current/bootstrap/cache/config.php ]; then
              grep "'key'" /var/www/html/current/bootstrap/cache/config.php | head -1
            else
              echo "config cache not found"
            fi
            
            echo ""
            echo "=== 権限確認 ==="
            ls -la /var/www/html/current/storage/
            ls -la /var/www/html/current/storage/framework/
            ls -la /var/www/html/current/storage/framework/sessions/
            
            echo ""
            echo "=== PHP情報 ==="
            php -v
            php -m | grep -E "(session|openssl|mbstring|pdo_mysql)"
            
            echo ""
            echo "=== Livewireアセット確認 ==="
            ls -la /var/www/html/current/public/vendor/ 2>/dev/null || echo "vendor directory not found"
            if [ -d /var/www/html/current/public/vendor/livewire ]; then
              ls -la /var/www/html/current/public/vendor/livewire/
            else
              echo "Livewire assets not found"
            fi
            
            echo ""
            echo "=== Livewireマニフェスト確認 ==="
            if [ -f /var/www/html/current/bootstrap/cache/livewire-components.php ]; then
              echo "Livewire manifest exists"
              wc -l /var/www/html/current/bootstrap/cache/livewire-components.php
            else
              echo "Livewire manifest not found"
            fi
          EOF
          
          rm key.pem