name: Check Login 500 Error

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check login error logs
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # SSHキー設定
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          # EC2に接続してログ確認
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'EOF'
            echo "=== Checking Laravel Logs ==="
            cd /var/www/xsyumeno
            
            # 最新のエラーログ確認
            echo "=== Latest Error Logs ==="
            tail -n 100 storage/logs/laravel.log | grep -A 5 -B 5 "ERROR\|500\|login"
            
            # セッション設定確認
            echo -e "\n=== Session Configuration ==="
            grep -E "SESSION_DRIVER|SESSION_DOMAIN" .env
            
            # セッションディレクトリの権限確認
            echo -e "\n=== Session Directory Permissions ==="
            ls -la storage/framework/sessions/
            
            # データベース接続確認
            echo -e "\n=== Database Connection Test ==="
            php artisan tinker --execute="echo 'DB Connection: ' . (DB::connection()->getPdo() ? 'OK' : 'Failed');"
            
            # ルート確認
            echo -e "\n=== Login Routes ==="
            php artisan route:list | grep -E "login|auth"
            
            # Livewireコンポーネント確認
            echo -e "\n=== Livewire Components ==="
            ls -la app/Livewire/ 2>/dev/null || echo "Livewire directory not found"
            ls -la app/Http/Livewire/ 2>/dev/null || echo "Http/Livewire directory not found"
            
            # キャッシュクリア
            echo -e "\n=== Clearing Caches ==="
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            
            # 再度ログ確認
            echo -e "\n=== Latest Logs After Cache Clear ==="
            tail -n 50 storage/logs/laravel.log
          EOF
          
          rm key.pem