name: Check Vision Data
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check vision data
        uses: appleboy/ssh-action@master
        with:
          host: 54.64.54.226
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat > /tmp/check_vision.php << 'PHPEOF'
            <?php
            require '/var/www/html/vendor/autoload.php';
            $app = require_once '/var/www/html/bootstrap/app.php';
            $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
            $kernel->bootstrap();

            use App\Models\MedicalRecord;

            $record = MedicalRecord::find(132);
            echo "=== カルテ132の視力データ ===\n";
            echo json_encode($record->vision_records, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
            echo "\n";
            PHPEOF

            php /tmp/check_vision.php
