name: Check and Fix Structure

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check structure and fix
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== Current Structure ==="
            ls -la | head -20
            
            echo -e "\n=== Checking for public directory ==="
            if [ -d "public" ]; then
              echo "public/ exists:"
              ls -la public/ | head -10
            else
              echo "public/ does NOT exist"
            fi
            
            echo -e "\n=== Checking index.php location ==="
            find . -name "index.php" -type f | head -5
            
            echo -e "\n=== Current Nginx root ==="
            grep "root" /etc/nginx/sites-enabled/* 
            
            # publicディレクトリが存在する場合の修正
            if [ -d "public" ]; then
              echo -e "\n=== Fixing Nginx for public directory ==="
              sudo tee /etc/nginx/sites-available/xsyumeno > /dev/null << 'NGINX'
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              
              root /var/www/html/current/public;
              index index.php index.html;
              
              server_name _;
              
              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }
              
              location ~ \.php$ {
                  fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }
              
              location ~ /\.(?!well-known).* {
                  deny all;
              }
          }
          NGINX
              
              sudo rm -f /etc/nginx/sites-enabled/*
              sudo ln -s /etc/nginx/sites-available/xsyumeno /etc/nginx/sites-enabled/
              sudo nginx -t
              sudo systemctl restart nginx
              
              echo "Nginx updated to serve from /var/www/html/current/public"
            fi
            
            # 権限再確認
            echo -e "\n=== Fixing Permissions ==="
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            if [ -d "storage" ]; then
              sudo chmod -R 777 storage
            fi
            if [ -d "bootstrap/cache" ]; then  
              sudo chmod -R 777 bootstrap/cache
            fi
            
            # 最終テスト
            echo -e "\n=== Final Test ==="
            curl -I http://localhost/
            curl -I http://localhost/admin/login
            
            # エラーログ
            echo -e "\n=== Recent Nginx Errors ==="
            sudo tail -10 /var/log/nginx/error.log
          EOF
          
          rm key.pem