name: Check SMS Logs

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check SMS Log Format
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: 54.64.54.226
        EC2_USER: ubuntu
      run: |
        echo "$EC2_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${EC2_USER}@${EC2_HOST} << 'REMOTE'
        echo "=== SMS送信ログサンプル（最新10件） ==="
        sudo grep -E 'SMS送信|SMS.*成功|sendSMS' /var/www/html/storage/logs/laravel-2025-10-19.log | tail -n 10
        REMOTE

        rm deploy_key.pem
