name: Check Store 8 Managers

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check Store 8 Managers
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: 54.64.54.226
        EC2_USER: ubuntu
      run: |
        echo "$EC2_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${EC2_USER}@${EC2_HOST} << 'REMOTE'
        cd /var/www/html

        sudo php artisan tinker --execute="
        echo \"=== 藤沢店（ID 8）の管理者 ===\n\";

        \$store = App\Models\Store::find(8);
        echo \"Store: {\$store->name}\n\n\";

        echo \"=== store_managers テーブル ===\n\";
        \$managers = DB::table('store_managers')->where('store_id', 8)->get();
        foreach (\$managers as \$m) {
            \$user = App\Models\User::find(\$m->user_id);
            if (\$user) {
                echo \"User ID: {\$m->user_id}, Email: {\$user->email}, Name: {\$user->name}\n\";
            }
        }
        echo \"\n\";

        echo \"=== store_id = 8 のユーザー（全員） ===\n\";
        \$users = App\Models\User::where('store_id', 8)->get();
        foreach (\$users as \$u) {
            echo \"User ID: {\$u->id}, Email: {\$u->email}, Name: {\$u->name}, Active: \" . (\$u->is_active ? 'Y' : 'N') . \"\n\";
        }
        "
        REMOTE

        rm deploy_key.pem
