name: Check Code

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check AdminNotificationService
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: 54.64.54.226
        EC2_USER: ubuntu
      run: |
        echo "$EC2_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${EC2_USER}@${EC2_HOST} '<<' 'CHECK'
        echo "=== Debug log check ==="
        sudo grep -n "Email notification check" /var/www/html/app/Services/AdminNotificationService.php || echo "NOT FOUND"
        CHECK

        rm deploy_key.pem
