name: Clear Customer Data

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DELETE" to confirm'
        required: true
        default: ''

jobs:
  clear-data:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DELETE'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Clear customer data on production server
      run: |
        aws ssm send-command \
          --instance-ids "i-061a146fcb1cc54ae" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["cd /var/www/html && chmod +x scripts/clear-customer-data.sh && ./scripts/clear-customer-data.sh"]' \
          --region ap-northeast-1 \
          --output table