name: Clear Test Data

on:
  workflow_dispatch:

jobs:
  clear-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clear test data on EC2
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "Clearing all test data completely..."
            
            # Delete stores using multiple methods
            sudo -u www-data php artisan tinker --execute="
            \App\Models\Store::query()->delete();
            \DB::table('stores')->truncate();
            echo 'All stores deleted!';
            "
            
            # Also clear any related data
            sudo -u www-data php artisan tinker --execute="
            \DB::table('customers')->delete();
            \DB::table('reservations')->delete();
            echo 'Related data cleared!';
            "
            
            # Clear application caches
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan view:clear
            
            echo "All test data completely cleared, admin users preserved"
          EOF
          
          rm key.pem