name: Create Admin User

on:
  workflow_dispatch:

jobs:
  create-admin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create admin user on EC2
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "Creating admin user..."
            sudo -u www-data php artisan tinker --execute="
            \App\Models\User::create([
                'name' => 'Administrator',
                'email' => 'admin@xsyumeno.com',
                'password' => \Hash::make('Admin123!'),
                'email_verified_at' => now()
            ]);
            echo 'Admin user created successfully!';
            "
            
            echo "Admin account ready: admin@xsyumeno.com / Admin123!"
          EOF
          
          rm key.pem