name: Create Proper Admin User

on:
  workflow_dispatch:

jobs:
  create-admin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create proper admin user
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== Deleting existing admin users ==="
            sudo -u www-data php artisan tinker --execute="
            \App\Models\User::where('email', 'admin@xsyumeno.com')->delete();
            echo 'Existing admin deleted';
            "
            
            echo "=== Creating proper admin user ==="
            sudo -u www-data php artisan tinker --execute="
            \$admin = \App\Models\User::create([
                'name' => 'Administrator',
                'email' => 'admin@xsyumeno.com', 
                'password' => \Hash::make('Admin123!'),
                'role' => 'superadmin',
                'is_active' => true,
                'email_verified_at' => now()
            ]);
            echo 'Admin created with ID: ' . \$admin->id;
            echo 'Email: ' . \$admin->email;
            echo 'Role: ' . \$admin->role;
            echo 'Active: ' . (\$admin->is_active ? 'Yes' : 'No');
            "
            
            echo "=== Verifying admin access ==="
            sudo -u www-data php artisan tinker --execute="
            \$user = \App\Models\User::where('email', 'admin@xsyumeno.com')->first();
            if (\$user) {
                echo 'Admin found: ' . \$user->email;
                echo 'Role: ' . \$user->role;
                echo 'Active: ' . (\$user->is_active ? 'Yes' : 'No');
                echo 'Can access panel: ' . (\$user->canAccessPanel(app('filament')->getPanel('admin')) ? 'Yes' : 'No');
            } else {
                echo 'Admin NOT found!';
            }
            "
            
            # Clear caches
            sudo -u www-data php artisan config:clear
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan config:cache
            
            echo "=== Admin creation complete ==="
          EOF
          
          rm key.pem