name: Debug Status

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug current status
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'SSHEOF' || echo "SSH connection failed"
            echo "=== Server Status Check ==="
            
            echo "1. Directory structure:"
            ls -la /var/www/html/ || echo "html directory issue"
            
            echo ""
            echo "2. Current directory:"
            ls -la /var/www/html/current/ 2>/dev/null || echo "current not found"
            
            echo ""
            echo "3. Public directory:"
            ls -la /var/www/html/current/public/ 2>/dev/null || echo "public not found"
            
            echo ""
            echo "4. Index.php check:"
            [ -f /var/www/html/current/public/index.php ] && echo "EXISTS" || echo "MISSING"
            
            echo ""
            echo "5. Nginx config root:"
            grep "root" /etc/nginx/sites-available/default
            
            echo ""
            echo "6. Services status:"
            systemctl is-active nginx
            systemctl is-active php8.3-fpm
            
            echo ""
            echo "7. Error logs:"
            sudo tail -5 /var/log/nginx/error.log 2>/dev/null || echo "No nginx error log"
            
            echo ""
            echo "8. Disk space:"
            df -h /var/www/html/
            
            echo ""
            echo "=== Emergency Fix ==="
            if [ ! -d "/var/www/html/current" ]; then
              echo "Creating missing directories..."
              sudo mkdir -p /var/www/html/current/public
              echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/current/public/index.php > /dev/null
              sudo chown -R www-data:www-data /var/www/html/current
            fi
            
            if [ ! -f "/var/www/html/current/public/index.php" ]; then
              echo "Creating test index.php..."
              sudo mkdir -p /var/www/html/current/public
              echo "<?php echo 'Server is working!'; ?>" | sudo tee /var/www/html/current/public/index.php > /dev/null
              sudo chown -R www-data:www-data /var/www/html/current
            fi
            
            echo ""
            echo "=== Final Test ==="
            curl -s http://localhost/ | head -1 || echo "HTTP test failed"
          SSHEOF
          
          rm key.pem