name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to EC2
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: 13.115.38.179
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          # EC2にデプロイ
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST << 'EOF'
            cd /var/www/html/current
            
            echo "=== Pulling latest changes ==="
            git pull origin main
            
            echo "=== Installing dependencies ==="
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            echo "=== Running migrations ==="
            php artisan migrate --force
            
            echo "=== Clearing caches ==="
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            
            echo "=== Rebuilding cache ==="
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            echo "=== Setting permissions ==="
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .
            sudo chmod -R 777 storage bootstrap/cache
            
            echo "=== Restarting services ==="
            sudo systemctl restart php8.3-fpm
            sudo systemctl restart nginx
            
            echo "=== Testing deployment ==="
            curl -s -o /dev/null -w "Homepage: %{http_code}\n" http://localhost/
            curl -s -o /dev/null -w "Admin: %{http_code}\n" http://localhost/admin/login
            
            echo "=== Deployment complete ==="
            php artisan --version
          EOF
          
          rm key.pem
          
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi