name: Deploy to New Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy Laravel Application
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          # Deploy via SSH
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -i key.pem ubuntu@35.73.211.108 << 'EOF'
            echo "=== DEPLOYMENT STARTED ==="
            date
            
            # Clone application
            cd /var/www/html
            sudo rm -rf current
            git clone https://github.com/Naoki-Takahashi0420/metore_system.git current
            cd current
            
            # Environment configuration
            cat > .env << 'ENVFILE'
          APP_NAME=Xsyumeno
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://35.73.211.108
          
          LOG_CHANNEL=stack
          LOG_LEVEL=error
          
          DB_CONNECTION=mysql
          DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
          DB_PORT=3306
          DB_DATABASE=xsyumenodb
          DB_USERNAME=admin
          DB_PASSWORD=Xsyumeno2024#!
          
          CACHE_DRIVER=file
          SESSION_DRIVER=file
          QUEUE_CONNECTION=sync
          FILESYSTEM_DISK=local
          
          AWS_DEFAULT_REGION=ap-northeast-1
          ENVFILE
            
            # Install dependencies
            composer install --no-dev --optimize-autoloader
            
            # Laravel setup
            php artisan key:generate
            php artisan storage:link
            
            # Database migration
            php artisan migrate:fresh --force
            
            # Create admin user
            php artisan tinker --execute="
              \$user = App\Models\User::create([
                  'name' => 'Administrator',
                  'email' => 'admin@xsyumeno.com',
                  'password' => Hash::make('password'),
                  'role' => 'superadmin',
                  'is_active' => true,
                  'email_verified_at' => now()
              ]);
              echo 'Admin created: ' . \$user->email;
            "
            
            # Set permissions
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            sudo chmod -R 775 storage bootstrap/cache
            
            # Optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Restart services
            sudo systemctl restart nginx php8.3-fpm
            
            # Verify
            echo -e "\n=== DEPLOYMENT COMPLETE ==="
            echo "URL: http://35.73.211.108/admin/login"
            echo "Testing..."
            curl -I http://localhost/admin/login
          EOF
          
          rm key.pem