name: Simple Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, mbstring, xml
      
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          npm ci
          npm run build
      
      - name: Deploy to EC2
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          
          # Create deployment package (simplified)
          tar -czf deploy.tar.gz .
          
          # Transfer files to EC2
          scp -o StrictHostKeyChecking=no -i deploy_key.pem deploy.tar.gz ubuntu@13.115.38.179:/tmp/
          
          # Simple deploy script
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@13.115.38.179 "
            cd /var/www/html && \
            sudo rm -rf current.old && \
            [ -d current ] && sudo mv current current.old || true && \
            sudo mkdir current && \
            sudo tar -xzf /tmp/deploy.tar.gz -C current && \
            sudo chown -R www-data:www-data current && \
            [ -f .env.production ] && sudo cp .env.production current/.env || true && \
            cd current && \
            sudo -u www-data php artisan config:cache && \
            sudo -u www-data php artisan route:cache && \
            sudo -u www-data php artisan view:cache && \
            sudo -u www-data php artisan migrate --force && \
            sudo -u www-data php artisan storage:link && \
            sudo systemctl reload php8.3-fpm && \
            sudo systemctl reload nginx && \
            rm /tmp/deploy.tar.gz && \
            echo 'Deployment completed!'
          "
          
          rm deploy_key.pem