name: Deploy Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laravel application
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'SSHEOF'
            echo "=== Laravel Application Deployment ==="
            
            # 現在のcurrentディレクトリをクリア
            sudo rm -rf /var/www/html/current/*
            
            # GitHubから最新コードをクローン
            cd /var/www/html/current
            git clone https://github.com/Naoki-Takahashi0420/metore_system.git .
            
            # .env設定
            cat > .env << 'ENVEOF'
APP_NAME=Xsyumeno
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://13.115.38.179

LOG_CHANNEL=stack
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=xsyumenodb
DB_USERNAME=admin
DB_PASSWORD=Xsyumeno2024#!

CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_CONNECTION=sync

MAIL_MAILER=log
ENVEOF
            
            # 権限設定
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            sudo chmod -R 775 storage bootstrap/cache
            
            # Composer install
            composer install --no-dev --optimize-autoloader
            
            # Laravel setup
            sudo -u www-data php artisan key:generate --force
            sudo -u www-data php artisan migrate --force
            
            # 管理者アカウント作成
            sudo -u www-data php artisan tinker --execute="
              use App\Models\User;
              User::where('email', 'admin@xsyumeno.com')->delete();
              \$admin = User::create([
                'name' => 'Administrator',
                'email' => 'admin@xsyumeno.com',
                'password' => bcrypt('password'),
                'role' => 'superadmin',
                'is_active' => true,
                'email_verified_at' => now()
              ]);
              echo 'Admin: ' . \$admin->email . ' (ID: ' . \$admin->id . ')';
            "
            
            # Filament assets
            sudo -u www-data php artisan filament:assets
            sudo -u www-data php artisan vendor:publish --all --force
            
            # Cache optimization
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            # Nginx設定を正しく更新
            sudo tee /etc/nginx/sites-available/default > /dev/null << 'NGINX'
            server {
                listen 80 default_server;
                listen [::]:80 default_server;
                server_name _;
                root /var/www/html/current/public;
                index index.php index.html index.htm;
                
                location / {
                    try_files $uri $uri/ /index.php?$query_string;
                }
                
                location ~ \.php$ {
                    include snippets/fastcgi-php.conf;
                    fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                    include fastcgi_params;
                }
                
                location ~ /\.(?!well-known).* {
                    deny all;
                }
            }
            NGINX
            
            # Nginx設定テストと再起動
            sudo nginx -t && sudo systemctl restart nginx
            sudo systemctl restart php8.3-fpm
            
            # 確認
            echo ""
            echo "=== Final Checks ==="
            echo "1. Laravel public/index.php:"
            [ -f public/index.php ] && echo "EXISTS" || echo "MISSING"
            
            echo ""
            echo "2. HTTP Test (root):"
            curl -s http://localhost/ | head -1 || echo "Root failed"
            
            echo ""
            echo "3. HTTP Test (admin/login):"
            curl -s -o /dev/null -w "Status: %{http_code}" http://localhost/admin/login
            
            echo ""
            echo "=== LARAVEL DEPLOYMENT COMPLETE ==="
            echo "URL: http://13.115.38.179/admin/login"
            echo "Email: admin@xsyumeno.com"
            echo "Password: password"
          SSHEOF
          
          rm key.pem