name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, mbstring, xml
      
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          npm ci
          npm run build
      
      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.env \
            --exclude=.github \
            --exclude=tests \
            --exclude=*.pem \
            --exclude=*.tar.gz \
            .
      
      - name: Deploy to EC2
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          # Transfer files
          scp -o StrictHostKeyChecking=no -i key.pem deploy.tar.gz ubuntu@13.115.38.179:/tmp/
          
          # Deploy script
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 '
            cd /var/www/html
            
            # Backup and extract
            [ -d current ] && sudo mv current backup_$(date +%Y%m%d_%H%M%S)
            sudo mkdir current
            sudo tar -xzf /tmp/deploy.tar.gz -C current
            sudo chown -R ubuntu:ubuntu current
            
            # Setup Laravel
            cd current
            [ -f /var/www/html/.env.production ] && cp /var/www/html/.env.production .env
            
            # Create directories
            mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache
            
            # Permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Laravel commands
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            php artisan storage:link
            
            # Restart services
            sudo systemctl reload php8.3-fpm
            sudo systemctl reload nginx
            
            # Cleanup
            rm /tmp/deploy.tar.gz
            
            echo "Deploy success!"
          '
          
          rm key.pem
