name: Deploy Laravel Now

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laravel application
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'EOF'
            echo "=== LARAVEL DEPLOYMENT ==="
            
            # Create temporary directory and clone Laravel app
            cd /tmp
            rm -rf laravel_temp
            git clone https://github.com/Naoki-Takahashi0420/metore_system.git laravel_temp
            
            # Clear current and move Laravel files
            sudo rm -rf /var/www/html/current/*
            sudo cp -r /tmp/laravel_temp/* /var/www/html/current/
            
            # Set up .env
            cd /var/www/html/current
            sudo tee .env > /dev/null << 'ENVEOF'
APP_NAME=Xsyumeno
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://13.115.38.179

DB_CONNECTION=mysql
DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=xsyumenodb
DB_USERNAME=admin
DB_PASSWORD=Xsyumeno2024#!

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_CONNECTION=sync
MAIL_MAILER=log
ENVEOF
            
            # Set permissions
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            sudo chmod -R 775 /var/www/html/current/storage
            sudo chmod -R 775 /var/www/html/current/bootstrap/cache
            
            # Update Nginx config to point to Laravel public directory
            sudo tee /etc/nginx/sites-available/default > /dev/null << 'NGINX_CONF'
server {
    listen 80 default_server;
    server_name _;
    root /var/www/html/current/public;
    index index.php index.html;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
NGINX_CONF
            
            # Install Composer dependencies
            composer install --no-dev --optimize-autoloader --no-interaction
            
            # Laravel setup
            sudo -u www-data php artisan key:generate --force
            sudo -u www-data php artisan migrate --force
            
            # Create admin user
            sudo -u www-data php artisan tinker --execute="
              use App\\Models\\User;
              User::where('email', 'admin@xsyumeno.com')->delete();
              \$admin = User::create([
                'name' => 'Administrator', 
                'email' => 'admin@xsyumeno.com',
                'password' => bcrypt('password'),
                'role' => 'superadmin',
                'is_active' => true,
                'email_verified_at' => now()
              ]);
              echo 'Admin created: ' . \$admin->email;
            "
            
            # Filament assets
            sudo -u www-data php artisan filament:assets
            
            # Cache optimization
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            # Test nginx config and restart
            sudo nginx -t && sudo systemctl restart nginx
            
            echo ""
            echo "=== DEPLOYMENT VERIFICATION ==="
            echo "Laravel public/index.php exists:"
            [ -f public/index.php ] && echo "YES" || echo "NO"
            
            echo ""
            echo "HTTP test:"
            curl -s -o /dev/null -w "Status: %{http_code}" http://localhost/admin/login
            
            echo ""
            echo "=== LARAVEL DEPLOYMENT COMPLETE ==="
            echo "URL: http://13.115.38.179/admin/login"
            echo "Email: admin@xsyumeno.com"
            echo "Password: password"
            
            # Cleanup
            rm -rf /tmp/laravel_temp
          EOF
          rm key.pem