name: Emergency Fix Now

on:
  push:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Emergency fix
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 'sudo mkdir -p /var/www/html/current/public && echo "<!DOCTYPE html><html><head><title>Xsyumeno Admin</title></head><body><h1>Xsyumeno System</h1><p>Admin panel is loading...</p><a href=\"/admin/login\">Login</a></body></html>" | sudo tee /var/www/html/current/public/index.php && echo "<?php echo \"Laravel is working!\"; ?>" | sudo tee /var/www/html/current/public/test.php && sudo chown -R www-data:www-data /var/www/html/current && echo "server { listen 80; root /var/www/html/current/public; index index.php index.html; location / { try_files \$uri \$uri/ /index.php?\$query_string; } location ~ \.php\$ { fastcgi_pass unix:/var/run/php/php8.3-fpm.sock; include fastcgi_params; fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name; } }" | sudo tee /etc/nginx/sites-available/default && sudo systemctl reload nginx'
          rm key.pem