name: Emergency Deploy NOW

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Direct Deploy without SSH
        run: |
          # Deploy script is public now, so we can download and show it
          echo "Deployment script available at:"
          echo "https://raw.githubusercontent.com/Naoki-Takahashi0420/metore_system/main/deploy.sh"
          echo ""
          echo "To deploy, run this command in EC2 Instance Connect:"
          echo "curl -s https://raw.githubusercontent.com/Naoki-Takahashi0420/metore_system/main/deploy.sh | sudo bash"
          echo ""
          echo "Checking if site is accessible:"
          curl -I http://13.231.41.238/admin/login || echo "Site not ready yet"