name: Final Login Fix

on:
  workflow_dispatch:

jobs:
  fix-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Final fix for login issues
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== ログファイル権限修正 ==="
            sudo touch storage/logs/laravel.log
            sudo chown www-data:www-data storage/logs/laravel.log
            sudo chmod 664 storage/logs/laravel.log
            
            echo ""
            echo "=== ストレージ権限完全修正 ==="
            sudo chown -R www-data:www-data storage
            sudo chown -R www-data:www-data bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
            
            echo ""
            echo "=== セッション設定確認・修正 ==="
            grep SESSION_ .env
            
            # セッションドメインをIPアドレスに設定
            sudo sed -i 's/SESSION_DOMAIN=.*/SESSION_DOMAIN=13.115.38.179/' .env
            
            # セッションセキュリティ設定を緩和（HTTPでも動作するように）
            sudo sed -i 's/SESSION_SECURE_COOKIE=.*/SESSION_SECURE_COOKIE=false/' .env
            
            echo ""
            echo "=== APP_URL修正 ==="
            sudo sed -i 's|APP_URL=.*|APP_URL=http://13.115.38.179|' .env
            grep APP_URL .env
            
            echo ""
            echo "=== キャッシュ完全クリア ==="
            sudo rm -rf bootstrap/cache/*.php
            sudo rm -rf storage/framework/cache/data/*
            sudo rm -rf storage/framework/sessions/*
            sudo rm -rf storage/framework/views/*
            
            echo ""
            echo "=== 管理者アカウント再作成（直接SQL） ==="
            mysql -h xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com -u admin -p'Xsyumeno2024#!' xsyumenodb << 'MYSQL_EOF'
            DELETE FROM users WHERE email = 'admin@xsyumeno.com';
            INSERT INTO users (name, email, password, role, is_active, email_verified_at, created_at, updated_at)
            VALUES (
              'Administrator',
              'admin@xsyumeno.com',
              '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
              'superadmin',
              1,
              NOW(),
              NOW(),
              NOW()
            );
            SELECT id, email, role FROM users WHERE email = 'admin@xsyumeno.com';
            MYSQL_EOF
            
            echo ""
            echo "=== キャッシュ再構築 ==="
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            echo ""
            echo "=== Livewire再設定 ==="
            sudo -u www-data php artisan livewire:discover
            
            echo ""
            echo "=== Filamentアセット公開 ==="
            sudo -u www-data php artisan filament:assets
            
            echo ""
            echo "=== サービス再起動 ==="
            sudo systemctl restart php8.3-fpm
            sudo systemctl restart nginx
            
            echo ""
            echo "=== ログインページテスト ==="
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/admin/login)
            echo "Login page status: $response"
            
            echo ""
            echo "=== セッションテスト ==="
            curl -c /tmp/cookies.txt -s http://localhost/admin/login | grep -o 'csrf-token.*content="[^"]*"' | head -1
            
            echo ""
            echo "================================"
            echo "FINAL FIX COMPLETE!"
            echo "================================"
            echo "Login URL: http://13.115.38.179/admin/login"
            echo "Email: admin@xsyumeno.com"
            echo "Password: password"
            echo "================================"
          EOF
          
          rm key.pem