name: Final Fix Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Final Deploy Fix
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem
        
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.112.39.129 << 'FINAL'
        echo "=== FINAL DEPLOYMENT FIX ==="
        
        # The repository is already cloned at /var/www/html
        cd /var/www/html
        
        # Fix permissions first
        echo "Fixing permissions..."
        sudo chown -R ubuntu:ubuntu /var/www/html
        
        # Install Composer globally
        if ! command -v composer &> /dev/null; then
          echo "Installing Composer..."
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
        fi
        
        # Now install dependencies as ubuntu user
        echo "Installing dependencies..."
        composer install --no-dev --optimize-autoloader
        
        # Create .env
        cat > .env << 'ENV'
        APP_NAME=Xsyumeno
        APP_ENV=production
        APP_KEY=base64:FhDmJJEPuQPAz6t5HMt6qTVSYLs7pJg7xLDgBEcVHHg=
        APP_DEBUG=false
        APP_URL=http://3.112.39.129
        
        DB_CONNECTION=mysql
        DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
        DB_PORT=3306
        DB_DATABASE=xsyumenodb
        DB_USERNAME=admin
        DB_PASSWORD=Xsyumeno2024#!
        
        LOG_CHANNEL=stack
        CACHE_DRIVER=file
        SESSION_DRIVER=file
        QUEUE_CONNECTION=sync
        ENV
        
        # Laravel setup
        php artisan key:generate
        php artisan storage:link
        php artisan config:clear
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
        # Now set correct permissions for web server
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html
        sudo chmod -R 775 storage bootstrap/cache
        
        # Restart services
        sudo systemctl restart nginx php8.3-fpm
        
        echo "=== Testing ==="
        curl -I http://localhost/
        
        echo "=== DEPLOYMENT COMPLETE ==="
        FINAL
        
        rm key.pem
        
        echo "Testing from outside..."
        curl http://3.112.39.129/ | head -20