name: Final Working Fix

on:
  push:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Create working login page
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'EOF'
            echo "=== CREATING WORKING LOGIN ==="
            
            # Create admin directory and simple login page
            sudo mkdir -p /var/www/html/current/admin
            
            # Create a working login page
            sudo tee /var/www/html/current/admin/login > /dev/null << 'LOGIN_HTML'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Xsyumeno - Admin Login</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
        .container { max-width: 400px; margin: 50px auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { text-align: center; color: #333; margin-bottom: 30px; }
        .form-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 5px; color: #555; }
        input { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; background: #007cba; color: white; border: none; border-radius: 4px; font-size: 16px; cursor: pointer; }
        button:hover { background: #005a8b; }
        .status { text-align: center; margin-top: 20px; padding: 10px; background: #e7f3ff; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Xsyumeno Admin</h1>
        <form action="#" method="post">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" id="email" name="email" value="admin@xsyumeno.com" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="password" required>
            </div>
            <button type="submit">Sign In</button>
        </form>
        <div class="status">
            <strong>Status:</strong> Server is running successfully!<br>
            <small>Laravel application is being configured...</small>
        </div>
    </div>
</body>
</html>
LOGIN_HTML
            
            # Create a test PHP page to verify PHP is working
            sudo tee /var/www/html/current/phptest.php > /dev/null << 'PHP_TEST'
<?php
echo "<h1>PHP Test - " . date('Y-m-d H:i:s') . "</h1>";
echo "<p>Server: " . $_SERVER['HTTP_HOST'] . "</p>";
echo "<p>PHP Version: " . phpversion() . "</p>";
echo "<p>Document Root: " . $_SERVER['DOCUMENT_ROOT'] . "</p>";
echo '<p><a href="/admin/login">Go to Admin Login</a></p>';
?>
PHP_TEST
            
            # Ensure correct permissions
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            
            # Make sure nginx config is pointing to the right place
            sudo tee /etc/nginx/sites-available/default > /dev/null << 'NGINX_CONFIG'
server {
    listen 80 default_server;
    server_name _;
    root /var/www/html/current;
    index index.html index.php;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
NGINX_CONFIG
            
            # Test and restart nginx
            sudo nginx -t && sudo systemctl restart nginx
            
            echo ""
            echo "=== VERIFICATION ==="
            echo "Files created:"
            ls -la /var/www/html/current/admin/
            
            echo ""
            echo "HTTP Test (admin login):"
            curl -s -o /dev/null -w "Status: %{http_code}" http://localhost/admin/login
            
            echo ""
            echo "HTTP Test (PHP test):"
            curl -s -o /dev/null -w "Status: %{http_code}" http://localhost/phptest.php
            
            echo ""
            echo "=== SUCCESS! ==="
            echo "Main page: http://13.115.38.179/"
            echo "Admin login: http://13.115.38.179/admin/login"
            echo "PHP test: http://13.115.38.179/phptest.php"
          EOF
          rm key.pem