name: Fix Nginx

on:
  push:
    branches: [ main ]

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Fix Nginx configuration
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'SSHEOF'
            echo "=== Nginx設定修正 ==="
            
            # 現在のディレクトリ確認
            echo "Current directory structure:"
            ls -la /var/www/html/current/ || ls -la /var/www/html/
            
            # Nginxサイト設定を正しく設定
            sudo tee /etc/nginx/sites-available/default > /dev/null << 'NGINX'
            server {
                listen 80 default_server;
                listen [::]:80 default_server;
                server_name _;
                root /var/www/html/current/public;
                index index.php index.html index.htm;
                
                location / {
                    try_files $uri $uri/ /index.php?$query_string;
                }
                
                location ~ \.php$ {
                    include snippets/fastcgi-php.conf;
                    fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                    include fastcgi_params;
                }
                
                location ~ /\.(?!well-known).* {
                    deny all;
                }
            }
            NGINX
            
            # 設定テスト
            sudo nginx -t
            
            # サービス再起動
            sudo systemctl restart nginx
            
            # 権限確認・修正
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            sudo chmod -R 775 /var/www/html/current/storage
            sudo chmod -R 775 /var/www/html/current/bootstrap/cache
            
            # Laravel基本設定
            cd /var/www/html/current
            
            # .envが存在しない場合は作成
            if [ ! -f .env ]; then
              echo "Creating .env file..."
              cp .env.example .env || echo "No .env.example found"
              
              # 基本設定を追記
              cat >> .env << 'ENVEOF'
APP_NAME=Xsyumeno
APP_ENV=production
APP_DEBUG=true
APP_URL=http://13.115.38.179
DB_CONNECTION=mysql
DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=xsyumenodb
DB_USERNAME=admin
DB_PASSWORD=Xsyumeno2024#!
CACHE_DRIVER=array
SESSION_DRIVER=file
QUEUE_CONNECTION=sync
MAIL_MAILER=log
ENVEOF
            fi
            
            # APP_KEY生成
            sudo -u www-data php artisan key:generate --force
            
            # 管理者アカウント作成
            sudo -u www-data php artisan tinker --execute="
              try {
                \$admin = new \App\Models\User();
                \$admin->name = 'Administrator';
                \$admin->email = 'admin@xsyumeno.com';
                \$admin->password = bcrypt('password');
                \$admin->role = 'superadmin';
                \$admin->is_active = true;
                \$admin->email_verified_at = now();
                \$admin->save();
                echo 'Admin created: ' . \$admin->id;
              } catch (\Exception \$e) {
                echo 'Error: ' . \$e->getMessage();
              }
            "
            
            # 最終確認
            echo ""
            echo "=== 確認 ==="
            echo "Public directory:"
            ls -la /var/www/html/current/public/
            
            echo ""
            echo "Index.php exists:"
            [ -f /var/www/html/current/public/index.php ] && echo "YES" || echo "NO"
            
            echo ""
            echo "HTTP test:"
            curl -I http://localhost/ || echo "Failed to connect"
            
            echo ""
            echo "=== 修正完了 ==="
          SSHEOF
          
          rm key.pem