name: Fix Livewire Correct Path

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fix Livewire at correct location
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== Current Application Status ==="
            pwd
            ls -la | head -5
            
            echo -e "\n=== Fixing Livewire 500 Error ==="
            
            # 1. APP_KEY確認と生成
            if ! grep -q "^APP_KEY=base64:" .env; then
              echo "Generating APP_KEY..."
              php artisan key:generate
            else
              echo "APP_KEY exists"
            fi
            
            # 2. 完全なキャッシュクリア
            echo "Clearing all caches..."
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan optimize:clear
            
            # キャッシュディレクトリも削除
            rm -rf bootstrap/cache/*.php
            rm -rf storage/framework/cache/data/*
            rm -rf storage/framework/sessions/*
            rm -rf storage/framework/views/*.php
            
            # 3. 権限修正（重要）
            echo "Fixing permissions..."
            sudo chown -R www-data:www-data storage
            sudo chown -R www-data:www-data bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
            
            # 4. Livewireアセット再発行
            echo "Re-publishing Livewire assets..."
            php artisan livewire:publish --force
            
            # 5. Composerオートローダー再生成
            echo "Regenerating autoloader..."
            composer dump-autoload -o
            
            # 6. デバッグモード一時的に有効化
            echo "Enabling debug mode temporarily..."
            sed -i 's/APP_DEBUG=false/APP_DEBUG=true/' .env
            
            # 7. 設定キャッシュ再生成
            echo "Regenerating config cache..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # 8. サービス再起動
            echo "Restarting services..."
            sudo systemctl restart php8.3-fpm
            sudo systemctl restart nginx
            
            # 9. エラーログ確認
            echo -e "\n=== Checking Error Logs ==="
            if [ -f "storage/logs/laravel.log" ]; then
              tail -n 50 storage/logs/laravel.log | grep -i "error\|exception\|livewire" || echo "No recent errors"
            else
              echo "No log file yet"
            fi
            
            # 10. Livewireコンポーネント確認
            echo -e "\n=== Livewire Components ==="
            find app -type f -name "*Login*.php" 2>/dev/null | head -5
            
            # 11. テスト実行
            echo -e "\n=== Testing Endpoints ==="
            
            # ホームページテスト
            echo "Testing homepage..."
            curl -s -o /dev/null -w "Homepage: %{http_code}\n" http://localhost/
            
            # 管理画面ログインページテスト
            echo "Testing admin login..."
            curl -s -o /dev/null -w "Admin login: %{http_code}\n" http://localhost/admin/login
            
            # Livewireエンドポイントテスト
            echo "Testing Livewire endpoint..."
            curl -X POST http://localhost/livewire/update \
              -H "Content-Type: application/json" \
              -H "X-CSRF-TOKEN: test" \
              -d '{"fingerprint":{"id":"test","name":"test"},"serverMemo":{},"updates":[]}' \
              -s -o /dev/null -w "Livewire: %{http_code}\n"
            
            echo -e "\n=== Fix Complete ==="
            echo "Application path: /var/www/html/current"
            echo "Admin URL: http://13.115.38.179/admin/login"
            echo "Credentials: admin@xsyumeno.com / password"
            echo ""
            echo "If still getting 500 error, check:"
            echo "1. Browser console for JavaScript errors"
            echo "2. Network tab for failed requests"
            echo "3. storage/logs/laravel.log for detailed errors"
          EOF
          
          rm key.pem