name: Fix Subscription End Dates

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: '実行確認 (yesを入力)'
        required: true
        default: ''

jobs:
  fix-subscription-dates:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Fix Script on Production
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_HOST: 54.64.54.226
          EC2_USER: ubuntu
        run: |
          echo "$EC2_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          # スクリプトをサーバーにコピー
          scp -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i deploy_key.pem \
            fix-subscription-end-dates.php \
            ${EC2_USER}@${EC2_HOST}:/var/www/html/

          # サーバーでスクリプト実行
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i deploy_key.pem ${EC2_USER}@${EC2_HOST} << 'ENDSSH'
            cd /var/www/html

            echo "=== サブスク契約終了日修正スクリプト実行 ==="
            echo "yes" | sudo php fix-subscription-end-dates.php

            echo ""
            echo "=== 実行完了 ==="
          ENDSSH

          rm deploy_key.pem
          echo "✅ 修正完了"
