name: Production Reset

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    
    steps:
      - name: Complete production reset
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'SSHEOF'
            echo "=== PRODUCTION RESET START ==="
            echo "Account: 273021981629"
            echo "Server: 13.115.38.179"
            
            # 1. サービス停止
            sudo systemctl stop nginx php8.3-fpm
            
            # 2. 完全クリーンアップ
            sudo rm -rf /var/www/html/*
            
            # 3. 新規クローン
            cd /var/www/html
            git clone https://github.com/Naoki-Takahashi0420/metore_system.git current
            cd current
            
            # 4. .env設定
            cat > .env << 'ENVEOF'
APP_NAME=Xsyumeno
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://13.115.38.179

LOG_CHANNEL=stack
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=xsyumenodb
DB_USERNAME=admin
DB_PASSWORD=Xsyumeno2024#!

CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_CONNECTION=sync

MAIL_MAILER=log
ENVEOF
            
            # 5. Composerとセットアップ
            composer install --no-dev --optimize-autoloader
            sudo chown -R www-data:www-data /var/www/html/current
            sudo chmod -R 755 /var/www/html/current
            sudo chmod -R 775 storage bootstrap/cache
            
            # 6. Laravel初期化
            sudo -u www-data php artisan key:generate --force
            sudo -u www-data php artisan migrate:fresh --force
            
            # 7. 管理者作成
            sudo -u www-data php artisan tinker --execute="
              use App\Models\User;
              \$admin = User::create([
                'name' => 'Administrator',
                'email' => 'admin@xsyumeno.com',
                'password' => bcrypt('password'),
                'role' => 'superadmin',
                'is_active' => true,
                'email_verified_at' => now()
              ]);
              echo 'Admin: ' . \$admin->email;
            "
            
            # 8. アセットとキャッシュ
            sudo -u www-data php artisan vendor:publish --all --force
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            # 9. サービス再開
            sudo systemctl start php8.3-fpm nginx
            
            # 10. 確認
            sleep 3
            curl -s -o /dev/null -w "Status: %{http_code}\n" http://localhost/admin/login
            
            echo "=== RESET COMPLETE ==="
            echo "URL: http://13.115.38.179/admin/login"
            echo "Email: admin@xsyumeno.com"
            echo "Password: password"
          SSHEOF
          
          rm key.pem