name: Real-time Error Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Real-time error investigation
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== Current Error Logs (last 30 lines) ==="
            tail -30 storage/logs/laravel.log 2>/dev/null || echo "No Laravel logs"
            
            echo ""
            echo "=== Nginx Error Logs (last 10 lines) ==="
            sudo tail -10 /var/log/nginx/error.log 2>/dev/null || echo "No nginx errors"
            
            echo ""
            echo "=== PHP-FPM Errors (last 10 lines) ==="
            sudo tail -10 /var/log/php8.3-fpm.log 2>/dev/null || echo "No php-fpm errors"
            
            echo ""
            echo "=== Test actual HTTP requests ==="
            echo "Testing root page:"
            curl -s -I http://localhost/ | head -3
            echo "Testing admin login:"
            curl -s -I http://localhost/admin/login | head -3
            echo "Testing stores page:"
            curl -s -I http://localhost/stores | head -3
            
            echo ""
            echo "=== Check for permission issues ==="
            ls -la storage/logs/
            ls -la bootstrap/cache/
            
            echo ""
            echo "=== Environment variables ==="
            grep -E "APP_ENV|APP_DEBUG|APP_KEY" .env | head -5
            
            echo ""
            echo "=== Artisan check ==="
            sudo -u www-data php artisan --version
            
            echo ""
            echo "=== Generate fresh logs by making requests ==="
            curl -s http://localhost/ > /dev/null
            curl -s http://localhost/admin/login > /dev/null
            curl -s http://localhost/stores > /dev/null
            
            echo "Fresh error logs after requests:"
            tail -5 storage/logs/laravel.log 2>/dev/null || echo "No new logs"
            
            echo ""
            echo "=== Checking if Laravel is working ==="
            sudo -u www-data php artisan route:list | head -10 || echo "Route list failed"
            
            echo "Real-time debug complete"
          EOF
          
          rm key.pem