name: Reset Database Completely

on:
  workflow_dispatch:

jobs:
  reset-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Reset database and create admin
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
            cd /var/www/html/current
            
            echo "=== Completely resetting database ==="
            
            # Fresh migration with seed
            sudo -u www-data php artisan migrate:fresh --force
            
            echo "=== Creating admin user ==="
            sudo -u www-data php artisan tinker --execute="
            \$admin = \App\Models\User::create([
                'name' => 'Administrator', 
                'email' => 'admin@xsyumeno.com',
                'password' => \Hash::make('Admin123!'),
                'email_verified_at' => now()
            ]);
            echo 'Admin created with ID: ' . \$admin->id;
            echo 'Email: ' . \$admin->email;
            "
            
            echo "=== Verifying admin user ==="
            sudo -u www-data php artisan tinker --execute="
            \$user = \App\Models\User::where('email', 'admin@xsyumeno.com')->first();
            if (\$user) {
                echo 'Admin user exists: ' . \$user->email;
                echo 'User ID: ' . \$user->id;
            } else {
                echo 'Admin user NOT found!';
            }
            "
            
            echo "=== Checking stores table ==="
            sudo -u www-data php artisan tinker --execute="
            \$count = \App\Models\Store::count();
            echo 'Stores count: ' . \$count;
            "
            
            # Clear all caches
            sudo -u www-data php artisan config:clear
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan view:clear
            sudo -u www-data php artisan config:cache
            
            echo "=== Database reset complete ==="
          EOF
          
          rm key.pem