name: Emergency Reset Now

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Emergency reset
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 'sudo systemctl stop nginx php8.3-fpm; sudo rm -rf /var/www/html/current; sudo mkdir -p /var/www/html/current; cd /var/www/html/current; git clone https://github.com/Naoki-Takahashi0420/metore_system.git .; echo "APP_NAME=Xsyumeno" > .env; echo "APP_ENV=production" >> .env; echo "APP_DEBUG=true" >> .env; echo "APP_URL=http://13.115.38.179" >> .env; echo "DB_CONNECTION=mysql" >> .env; echo "DB_HOST=xsyumeno-db.cbq0ywo44b0p.ap-northeast-1.rds.amazonaws.com" >> .env; echo "DB_DATABASE=xsyumenodb" >> .env; echo "DB_USERNAME=admin" >> .env; echo "DB_PASSWORD=Xsyumeno2024#!" >> .env; echo "CACHE_DRIVER=array" >> .env; echo "SESSION_DRIVER=file" >> .env; sudo chown -R www-data:www-data .; composer install --no-dev; sudo -u www-data php artisan key:generate --force; sudo -u www-data php artisan migrate:fresh --force; sudo systemctl start php8.3-fpm nginx'
          rm key.pem
