name: Test Minimal Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test EC2 Connection
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.115.38.179 "echo 'Connection OK' && ls -la /var/www/html/current 2>/dev/null || echo 'No current deployment'"
          rm key.pem
