name: Test Login

on:
  push:
    paths:
      - '.github/workflows/test-login.yml'

jobs:
  test-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test admin login functionality
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'EOF'
          cd /var/www/html/current
          
          echo "=== Checking database connectivity ==="
          mysql -h localhost -u metore_user -ppassword123 -e "USE metore_database; SELECT COUNT(*) as user_count FROM users;"
          
          echo "=== Checking admin user directly ==="
          mysql -h localhost -u metore_user -ppassword123 -e "USE metore_database; SELECT id, email, role, is_active FROM users WHERE email='admin@xsyumeno.com';"
          
          echo "=== Creating admin user directly in database ==="
          mysql -h localhost -u metore_user -ppassword123 -e "USE metore_database; INSERT IGNORE INTO users (name, email, password, role, is_active, email_verified_at, created_at, updated_at) VALUES ('Administrator', 'admin@xsyumeno.com', '\$2y\$12\$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'superadmin', 1, NOW(), NOW(), NOW());"
          
          echo "=== Verify admin user created ==="
          mysql -h localhost -u metore_user -ppassword123 -e "USE metore_database; SELECT id, email, role, is_active FROM users WHERE email='admin@xsyumeno.com';"
          
          echo "=== Testing web connectivity ==="
          curl -I http://localhost/admin/login
          
          echo "=== Testing from external ==="  
          curl -I http://13.115.38.179/admin/login
          
          echo "========================================"
          echo "LOGIN TEST COMPLETE!"
          echo "========================================"
          echo "Login URL: http://13.115.38.179/admin/login"
          echo "Email: admin@xsyumeno.com"
          echo "Password: password"
          echo "Note: Admin user created directly in database"
          echo "========================================"
          EOF
          
          rm key.pem