name: Ultimate Fix

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ultimate fix for login
        env:
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          
          # まずローカルのファイルをEC2に転送
          scp -o StrictHostKeyChecking=no -i key.pem \
            .env.production \
            ubuntu@13.115.38.179:/tmp/.env.new
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@13.115.38.179 << 'SSHEOF'
            cd /var/www/html/current
            
            echo "=== 現在のエラーを詳細確認 ==="
            sudo tail -50 storage/logs/laravel.log 2>/dev/null | grep -A 10 "500\|error\|Error" || echo "No recent errors"
            
            echo ""
            echo "=== .envファイル完全再設定 ==="
            sudo cp /tmp/.env.new .env
            sudo sed -i 's|APP_URL=.*|APP_URL=http://13.115.38.179|' .env
            sudo sed -i 's/APP_DEBUG=.*/APP_DEBUG=true/' .env
            sudo sed -i 's/CACHE_DRIVER=.*/CACHE_DRIVER=file/' .env
            sudo sed -i 's/SESSION_DRIVER=.*/SESSION_DRIVER=file/' .env
            
            echo ""
            echo "=== APP_KEY再生成 ==="
            sudo -u www-data php artisan key:generate --force
            
            echo ""
            echo "=== 完全クリーンアップ ==="
            sudo rm -rf bootstrap/cache/*
            sudo rm -rf storage/framework/cache/*
            sudo rm -rf storage/framework/sessions/*
            sudo rm -rf storage/framework/views/*
            sudo rm -rf storage/logs/*
            
            echo ""
            echo "=== ディレクトリ再作成と権限設定 ==="
            sudo mkdir -p storage/framework/{cache/data,sessions,views}
            sudo mkdir -p storage/logs
            sudo mkdir -p bootstrap/cache
            sudo touch storage/logs/laravel.log
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            echo ""
            echo "=== Composer最適化 ==="
            sudo -u www-data composer install --no-dev --optimize-autoloader
            sudo -u www-data composer dump-autoload --optimize
            
            echo ""
            echo "=== Laravelの完全リセット ==="
            sudo -u www-data php artisan config:clear
            sudo -u www-data php artisan route:clear
            sudo -u www-data php artisan view:clear
            sudo -u www-data php artisan cache:clear
            
            echo ""
            echo "=== Livewire完全再セットアップ ==="
            sudo -u www-data php artisan vendor:publish --tag=livewire:config --force
            sudo -u www-data php artisan vendor:publish --tag=livewire:assets --force
            sudo -u www-data php artisan livewire:discover
            
            echo ""
            echo "=== Filament再セットアップ ==="
            sudo -u www-data php artisan filament:upgrade
            sudo -u www-data php artisan filament:assets
            
            echo ""
            echo "=== 管理者アカウント確実に作成 ==="
            sudo -u www-data php artisan tinker --execute="
              use App\Models\User;
              User::where('email', 'admin@xsyumeno.com')->delete();
              \$admin = User::create([
                'name' => 'Administrator',
                'email' => 'admin@xsyumeno.com',
                'password' => bcrypt('password'),
                'role' => 'superadmin',
                'is_active' => true,
                'email_verified_at' => now()
              ]);
              echo 'Admin created: ' . \$admin->id . ' - ' . \$admin->email;
            "
            
            echo ""
            echo "=== キャッシュ最適化 ==="
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            echo ""
            echo "=== PHP-FPM設定確認 ==="
            sudo sed -i 's/;clear_env = no/clear_env = no/' /etc/php/8.3/fpm/pool.d/www.conf
            
            echo ""
            echo "=== サービス完全再起動 ==="
            sudo systemctl restart php8.3-fpm
            sudo systemctl restart nginx
            
            echo ""
            echo "=== 動作確認 ==="
            sleep 3
            
            # ログインページ確認
            echo "Login page test:"
            curl -s -o /dev/null -w "%{http_code}" http://localhost/admin/login
            
            # Livewire JS確認
            echo ""
            echo "Livewire JS test:"
            curl -s -o /dev/null -w "%{http_code}" http://localhost/livewire/livewire.min.js
            
            # エラーログ最終確認
            echo ""
            echo "=== 最新のエラー（もしあれば） ==="
            sudo tail -20 storage/logs/laravel.log 2>/dev/null | grep -i error || echo "No errors"
            
            echo ""
            echo "=== デバッグモード無効化 ==="
            sudo sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' .env
            sudo -u www-data php artisan config:cache
            
            echo ""
            echo "================================"
            echo "ULTIMATE FIX COMPLETE!"
            echo "================================"
            echo "URL: http://13.115.38.179/admin/login"
            echo "Email: admin@xsyumeno.com"
            echo "Password: password"
            echo "================================"
          SSHEOF
          
          rm key.pem
