name: Update Store Business Hours

on:
  workflow_dispatch:
    inputs:
      store_name:
        description: 'Store name pattern (like %銀座%)'
        required: true
        default: '%銀座%'
      open_time:
        description: 'Opening time (HH:MM:SS)'
        required: true
        default: '10:00:00'
      close_time:
        description: 'Closing time (HH:MM:SS)'
        required: true
        default: '22:00:00'

jobs:
  update-store-hours:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Update store business hours
      run: |
        aws ssm send-command \
          --instance-ids "i-061a146fcb1cc54ae" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[\"cd /var/www/html && php artisan tinker --execute=\\\"\\\\\\$store = App\\\\\\\\\\\\\\\\Models\\\\\\\\\\\\\\\\Store::where('name', 'like', '${{ github.event.inputs.store_name }}')->first(); if (\\\\\\$store) { \\\\\\$businessHours = []; foreach(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] as \\\\\\$day) { \\\\\\$businessHours[] = ['day' => \\\\\\$day, 'open_time' => '${{ github.event.inputs.open_time }}', 'close_time' => '${{ github.event.inputs.close_time }}', 'is_closed' => false]; } \\\\\\$store->business_hours = \\\\\\$businessHours; \\\\\\$store->save(); echo 'Updated: ' . \\\\\\$store->name . ' to ${{ github.event.inputs.open_time }}-${{ github.event.inputs.close_time }}'; } else { echo 'Store not found: ${{ github.event.inputs.store_name }}'; }\\\"\"]" \
          --region ap-northeast-1 \
          --output table